In [266]:
### Import Packages:

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

import re

import holidays

import seaborn as sns
from scipy.stats import norm

from sklearn.preprocessing import LabelEncoder

In [267]:
### The data is password-protected. Thus, we can use the msoffcrypto-tool library to decrypt it first, then read it with pandas.
#!pip install msoffcrypto-tool

import sys
#!{sys.executable} -m pip install msoffcrypto-tool

#This forces pip to install into the exact same Python that your Jupyter kernel is using.
#After it finishes installing, restart your kernel (Kernel → Restart) and try the import again.

In [268]:
import msoffcrypto
import io

In [269]:
# Open the encrypted file
with open("Result.xlsx", "rb") as f:
    office_file = msoffcrypto.OfficeFile(f)
    office_file.load_key(password="EstFz2023")  # Enter your password here
    
    # Decrypt into a buffer
    decrypted = io.BytesIO()
    office_file.decrypt(decrypted)

In [270]:
# Read the decrypted buffer with pandas
df_original = pd.read_excel(decrypted)

In [271]:
df_original.head()

,Unnamed: 0,Client.ID..Anonymized.,Client.Visit.ID..Anonymized.,postalcode,EmergencyDepartment,ModeOfArrival,gender,Age.at.extract,Point.of.Arrival,Triage.Start.Time,...,Consult.Service,Initial.Assessment,First.MD.Key,Last.contact.and.decision.to.discharge,Disposition.Decision,LOS.Hours,Wait.Time.Hours,revisit.delay..Hours.,Revisit.within.48.hours,Revisit.within.72.hours
0,1,246749,925668,R2L0J5,SBGH,Wheelchair,Male,90.0,2016-10-06 14:05:00,2016-10-06 14:07:00,...,GI Bleed Team,2016-10-06 21:06:00,198.0,2016-10-07 12:18:00,ED Home,22.216667,7.000000,NaN,NaN,NaN
1,2,319344,65580,R3T1R2,SBGH,Walking,Female,98.0,2015-10-14 02:09:00,2015-10-14 02:09:00,...,IM-B,2015-10-14 03:32:00,192.0,2015-10-14 13:46:00,ED TRSF to IP,40.383333,1.383333,NaN,NaN,NaN
2,3,141192,435664,R2M0M6,SBGH,Walking/Wheelchair/Other (walk-in),Female,57.0,2018-02-20 10:11:00,2018-02-20 10:13:00,...,NaN,2018-02-20 16:18:00,1590.0,2018-02-20 18:56:00,ED Home,8.766667,6.100000,NaN,NaN,NaN
3,4,141192,845811,R2M0M6,SBGH,Walking,Female,57.0,2017-01-26 10:50:00,2017-01-26 10:51:00,...,NaN,2017-01-26 15:27:00,1635.0,2017-01-26 16:55:00,Home,6.083333,4.616667,NaN,NaN,NaN
4,5,160336,670600,R2L0R8,HSC-A,Other,Female,40.0,2014-05-05 17:53:00,2014-05-05 17:59:00,...,NaN,2014-05-05 22:52:00,1919.0,2014-05-05 23:05:00,ED Home,5.316667,4.950000,NaN,NaN,NaN

In [272]:
df_original.tail()

,Unnamed: 0,Client.ID..Anonymized.,Client.Visit.ID..Anonymized.,postalcode,EmergencyDepartment,ModeOfArrival,gender,Age.at.extract,Point.of.Arrival,Triage.Start.Time,...,Consult.Service,Initial.Assessment,First.MD.Key,Last.contact.and.decision.to.discharge,Disposition.Decision,LOS.Hours,Wait.Time.Hours,revisit.delay..Hours.,Revisit.within.48.hours,Revisit.within.72.hours
985265,985266,41619,468582,E2X0K9,HSC-P,Carried,Male,7.0,2017-07-03 23:52:00,2017-07-03 23:52:00,...,NaN,2017-07-04 05:55:00,1135.0,2017-07-04 05:55:00,ED Home,6.05,6.016667,NaN,NaN,NaN
985266,985267,255837,933542,R3B2P8,HSC-A,Walking,Female,40.0,2016-07-13 19:50:00,2016-07-13 20:10:00,...,NaN,NaT,NaN,2016-07-13 20:10:00,ED Reg LWBS,1.25,0.350000,NaN,NaN,NaN
985267,985268,233419,848227,R3W1E1,HSC-P,Carried,Male,7.0,2017-11-07 20:01:00,2017-11-07 20:01:00,...,NaN,2017-11-07 21:17:00,1135.0,2017-11-07 21:45:00,ED Home,1.75,0.866667,NaN,NaN,NaN
985268,985269,118659,933655,R0B0T0,HSC-P,Carried,Female,7.0,2017-09-04 12:46:00,2017-09-04 12:46:00,...,NaN,2017-09-04 13:32:00,166.0,2017-09-04 13:48:00,ED Home,1.05,0.616667,NaN,NaN,NaN
985269,985270,117534,802858,R3Y0A7,HSC-P,Stroller,Female,7.0,2017-11-22 09:36:00,2017-11-22 09:36:00,...,NaN,2017-11-22 12:31:00,912.0,2017-11-22 12:45:00,ED Home,3.15,2.833333,NaN,NaN,NaN

In [273]:
df_original.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 985270 entries, 0 to 985269
Data columns (total 32 columns):
 #   Column                                                 Non-Null Count   Dtype
---  ------                                                 --------------   -----
 0   Unnamed: 0                                             985270 non-null  int64
 1   Client.ID..Anonymized.                                 985270 non-null  int64
 2   Client.Visit.ID..Anonymized.                           985270 non-null  int64
 3   postalcode                                             972349 non-null  object
 4   EmergencyDepartment                                    985270 non-null  object
 5   ModeOfArrival                                          985269 non-null  object
 6   gender                                                 985270 non-null  object
 7   Age.at.extract                                         985268 non-null  float64
 8   Point.of.Arrival                                       985270 non-null  datetime64[ns]
 9   Triage.Start.Time                                      982293 non-null  datetime64[ns]
 10  CTAS.Score                                             985270 non-null  object
 11  EDComplaintCategory                                    985152 non-null  object
 12  EDChiefComplaint                                       985152 non-null  object
 13  ICD10.Code1                                            194351 non-null  object
 14  ICD10.Code2                                            13025 non-null   object
 15  Total.Lab.orders                                       521295 non-null  float64
 16  Total.LAB.Tests.ordered                                521295 non-null  float64
 17  Average.Time.to.Perform.a.Lab.Order..Minutes.          489278 non-null  float64
 18  Total.Diagnostic.orders                                350492 non-null  float64
 19  Total.Diagnostics.Tests.ordered                        350492 non-null  float64
 20  Average.Time.to.Perform.a.Diagnostics.Order..Minutes.  336232 non-null  float64
 21  provider.Type                                          799206 non-null  object
 22  Consult.Service                                        240951 non-null  object
 23  Initial.Assessment                                     798245 non-null  datetime64[ns]
 24  First.MD.Key                                           799206 non-null  float64
 25  Last.contact.and.decision.to.discharge                 985207 non-null  datetime64[ns]
 26  Disposition.Decision                                   985270 non-null  object
 27  LOS.Hours                                              985262 non-null  float64
 28  Wait.Time.Hours                                        985158 non-null  float64
 29  revisit.delay..Hours.                                  14054 non-null   float64
 30  Revisit.within.48.hours                                6003 non-null    float64
 31  Revisit.within.72.hours                                14054 non-null   float64
dtypes: datetime64[ns](4), float64(13), int64(3), object(12)
memory usage: 240.5+ MB

**Data:**

There are 31 variables. The first column is an index column. Some of the columns contain a significantly high number of missing values.

In the original version the main dtypes are datetime64[n], float64(13), int64(3), object(12)

Next, our goal is to understand the data.
How many unique/missing values are in certain columns?

**Clean Data and Feature Engineering:**

In [274]:
df_original['Client.ID..Anonymized.'].nunique()

### There are 370,714 unique client IDs

370714

In [275]:
print(df_original['Client.ID..Anonymized.'].isnull().sum())

### There are NO missing values in Client IDs.

0

In [276]:
df_original['Client.Visit.ID..Anonymized.'].nunique()

### There are 934,152 unique client visit IDs in the data. It seems that each visit will have a new visit ID.

934152

In [277]:
print(df_original['Client.Visit.ID..Anonymized.'].isnull().sum())

### There are NO missing values in Visit IDs.

0

In [278]:
len(df_original['Client.Visit.ID..Anonymized.']) - df_original['Client.Visit.ID..Anonymized.'].nunique()

### 51,118 client IDs appear more than once.

51118

In [279]:
### Identify unique visit IDs that appear more than once:

mul_visit_IDs = df_original[df_original['Client.Visit.ID..Anonymized.'].duplicated(keep=False)]['Client.Visit.ID..Anonymized.'].unique().tolist()

In [280]:
len(mul_visit_IDs)

### 41,339 unique visit IDs appear more than once.

41339

In [281]:
### Check records of client visit IDs that appear more than once.

### Example 1: Visit ID = 77
df_original[df_original['Client.Visit.ID..Anonymized.']==77]

,Unnamed: 0,Client.ID..Anonymized.,Client.Visit.ID..Anonymized.,postalcode,EmergencyDepartment,ModeOfArrival,gender,Age.at.extract,Point.of.Arrival,Triage.Start.Time,...,Consult.Service,Initial.Assessment,First.MD.Key,Last.contact.and.decision.to.discharge,Disposition.Decision,LOS.Hours,Wait.Time.Hours,revisit.delay..Hours.,Revisit.within.48.hours,Revisit.within.72.hours
119890,119891,320971,77,R2X0X4,SBGH,Municipal EMS,Male,67.0,2016-03-12 11:57:00,2016-03-12 12:02:00,...,ACSS,NaT,476.0,2016-03-12 20:13:00,ED TRSF to IP,9.966667,1.333333,NaN,NaN,NaN
777208,777209,320971,77,R2X0X4,SBGH,Municipal EMS,Male,67.0,2016-03-12 11:57:00,2016-03-12 12:02:00,...,Medicine,NaT,476.0,2016-03-12 20:13:00,ED TRSF to IP,9.966667,1.333333,NaN,NaN,NaN
812366,812367,320971,77,R2X0X4,SBGH,Municipal EMS,Male,67.0,2016-03-12 11:57:00,2016-03-12 12:02:00,...,Cardiology,NaT,476.0,2016-03-12 20:13:00,ED TRSF to IP,9.966667,1.333333,NaN,NaN,NaN

In [282]:
### Example 2: Visit ID = 90
df_original[df_original['Client.Visit.ID..Anonymized.']==90]

,Unnamed: 0,Client.ID..Anonymized.,Client.Visit.ID..Anonymized.,postalcode,EmergencyDepartment,ModeOfArrival,gender,Age.at.extract,Point.of.Arrival,Triage.Start.Time,...,Consult.Service,Initial.Assessment,First.MD.Key,Last.contact.and.decision.to.discharge,Disposition.Decision,LOS.Hours,Wait.Time.Hours,revisit.delay..Hours.,Revisit.within.48.hours,Revisit.within.72.hours
424778,424779,259321,90,R2K1Z3,SBGH,Ambulance - Local EMS,Female,38.0,2018-01-21 00:26:00,2018-01-21 00:32:00,...,O&G,2018-01-21 03:16:00,175.0,2018-01-21 14:34:00,ED TRSF to IP,14.366667,2.833333,NaN,NaN,NaN
873289,873290,259321,90,R2K1Z3,SBGH,Ambulance - Local EMS,Female,38.0,2018-01-21 00:26:00,2018-01-21 00:32:00,...,Obs/Gyne,2018-01-21 03:16:00,175.0,2018-01-21 14:34:00,ED TRSF to IP,14.366667,2.833333,NaN,NaN,NaN

**Note**:

It seems that when a client visits ID appears more than once, it is mainly due to different values of 'Consult.Service'.
The remaining columns/features have the same values.
Thus, we will aggregate 'Consult.Service' to a single record in case we decide to use that information later.

Moreover, there are a couple of columns in the data set that largely contain NAs (missing values): 'ICD10.Code1', 'ICD10.Code2', 'revisit.delay..Hours.', 'Revisit.within.48.hours', 'Revisit.within.72.hours'

We will remove these columns from the data after we have investigated them.

In [283]:
print(f'ICD10.Code1 Missing values: {df_original['ICD10.Code1'].isnull().sum()}')
print(f'ICD10.Code2 Missing values: {df_original['ICD10.Code2'].isnull().sum()}')
print(f'revisit.delay..Hours. Missing values: {df_original['revisit.delay..Hours.'].isnull().sum()}')
print(f'Revisit.within.48.hours Missing values: {df_original['Revisit.within.48.hours'].isnull().sum()}')
print(f'Revisit.within.72.hours Missing values: {df_original['Revisit.within.72.hours'].isnull().sum()}')

ICD10.Code1 Missing values: 790919
ICD10.Code2 Missing values: 972245
revisit.delay..Hours. Missing values: 971216
Revisit.within.48.hours Missing values: 979267
Revisit.within.72.hours Missing values: 971216

In [284]:
### When deleting the above features, we will also create a copy of the data frame.
### Make sure the original dataframe is not changed.

df_clean1 = df_original.drop(columns=['ICD10.Code1', 'ICD10.Code2', 'revisit.delay..Hours.', 'Revisit.within.48.hours', 'Revisit.within.72.hours'])

In [285]:
### Are there any missing values in 'Consult.Service'?

print(df_clean1['Consult.Service'].isnull().sum())

744319

In [286]:
### Are there any "UNKNOWN" values?

print(len(df_clean1[df_clean1['Consult.Service']=='UNKNOWN']))

0

In [287]:
# Split the data set into two datasets based on repeated visit IDs:

df_dupes = df_clean1[df_clean1['Client.Visit.ID..Anonymized.'].isin(mul_visit_IDs)]
df_clean = df_clean1[~df_clean1['Client.Visit.ID..Anonymized.'].isin(mul_visit_IDs)]

In [288]:
len(df_dupes)

92457

In [289]:
len(df_clean)

892813

Note: 92457 + 892813 = 985270 (Original number of records)

In [290]:
### Now we will focus on df_dupes.
### Note that in some rows, 'Consult.Service' is NaN

# Aggregation function: join non-NaN strings, preserve NaN if ALL values are NaN
def join_or_nan(x):
    valid = x.dropna()
    if valid.empty:
        return np.nan        # every row was NaN → preserve as NaN
    return ', '.join(valid.astype(str))   # skip NaNs, join the rest

In [291]:
# Step 1: build a dictionary for every column EXCEPT Visit ID and Consult.Service
# 'first' means: just take the first value (safe since all rows are identical anyway)
agg_dict = {col: 'first' for col in df_clean1.columns 
            if col not in ['Client.Visit.ID..Anonymized.', 'Consult.Service']}

# Step 2: add the special rule for Consult.Service separately
agg_dict['Consult.Service'] = join_or_nan

In [292]:
df_dupes_merged = (
    df_dupes
    .groupby('Client.Visit.ID..Anonymized.', as_index=False)
    .agg(agg_dict)
)

In [293]:
df_clean2 = pd.concat([df_clean, df_dupes_merged], ignore_index=True)

Verify the process:

In [294]:
df_clean2['Client.ID..Anonymized.'].nunique()

### The number of client IDs is the same as the number of client IDs in the original data

370714

In [295]:
df_clean2['Client.Visit.ID..Anonymized.'].nunique()

### The number of visit IDs is the same as the number of client IDs in the original data

934152

In [296]:
### Example 1: Visit ID = 77
df_clean2[df_clean2['Client.Visit.ID..Anonymized.']==77]

,Unnamed: 0,Client.ID..Anonymized.,Client.Visit.ID..Anonymized.,postalcode,EmergencyDepartment,ModeOfArrival,gender,Age.at.extract,Point.of.Arrival,Triage.Start.Time,...,Total.Diagnostics.Tests.ordered,Average.Time.to.Perform.a.Diagnostics.Order..Minutes.,provider.Type,Consult.Service,Initial.Assessment,First.MD.Key,Last.contact.and.decision.to.discharge,Disposition.Decision,LOS.Hours,Wait.Time.Hours
892816,119891,320971,77,R2X0X4,SBGH,Municipal EMS,Male,67.0,2016-03-12 11:57:00,2016-03-12 12:02:00,...,2.0,140.0,Physician,"ACSS, Medicine, Cardiology",NaT,476.0,2016-03-12 20:13:00,ED TRSF to IP,9.966667,1.333333

In [297]:
### Example 2: Visit ID = 90
df_clean2[df_clean2['Client.Visit.ID..Anonymized.']==90]

,Unnamed: 0,Client.ID..Anonymized.,Client.Visit.ID..Anonymized.,postalcode,EmergencyDepartment,ModeOfArrival,gender,Age.at.extract,Point.of.Arrival,Triage.Start.Time,...,Total.Diagnostics.Tests.ordered,Average.Time.to.Perform.a.Diagnostics.Order..Minutes.,provider.Type,Consult.Service,Initial.Assessment,First.MD.Key,Last.contact.and.decision.to.discharge,Disposition.Decision,LOS.Hours,Wait.Time.Hours
892818,424779,259321,90,R2K1Z3,SBGH,Ambulance - Local EMS,Female,38.0,2018-01-21 00:26:00,2018-01-21 00:32:00,...,4.0,307.0,Physician,"O&G, Obs/Gyne",2018-01-21 03:16:00,175.0,2018-01-21 14:34:00,ED TRSF to IP,14.366667,2.833333

In [298]:
### The number of records in the cleaned data set:

len(df_clean2['Client.Visit.ID..Anonymized.'])

934152

In [299]:
### Remove first column. It is an index column, and we do not need a separate index column.

df_clean2 = df_clean2.drop(columns=['Unnamed: 0'])
df_clean2.head()

,Client.ID..Anonymized.,Client.Visit.ID..Anonymized.,postalcode,EmergencyDepartment,ModeOfArrival,gender,Age.at.extract,Point.of.Arrival,Triage.Start.Time,CTAS.Score,...,Total.Diagnostics.Tests.ordered,Average.Time.to.Perform.a.Diagnostics.Order..Minutes.,provider.Type,Consult.Service,Initial.Assessment,First.MD.Key,Last.contact.and.decision.to.discharge,Disposition.Decision,LOS.Hours,Wait.Time.Hours
0,246749,925668,R2L0J5,SBGH,Wheelchair,Male,90.0,2016-10-06 14:05:00,2016-10-06 14:07:00,4,...,2.0,22.0,Physician,GI Bleed Team,2016-10-06 21:06:00,198.0,2016-10-07 12:18:00,ED Home,22.216667,7.000000
1,141192,435664,R2M0M6,SBGH,Walking/Wheelchair/Other (walk-in),Female,57.0,2018-02-20 10:11:00,2018-02-20 10:13:00,3,...,1.0,2.0,Physician,NaN,2018-02-20 16:18:00,1590.0,2018-02-20 18:56:00,ED Home,8.766667,6.100000
2,141192,845811,R2M0M6,SBGH,Walking,Female,57.0,2017-01-26 10:50:00,2017-01-26 10:51:00,2,...,1.0,8.0,Physician,NaN,2017-01-26 15:27:00,1635.0,2017-01-26 16:55:00,Home,6.083333,4.616667
3,160336,670600,R2L0R8,HSC-A,Other,Female,40.0,2014-05-05 17:53:00,2014-05-05 17:59:00,2,...,NaN,NaN,Physician,NaN,2014-05-05 22:52:00,1919.0,2014-05-05 23:05:00,ED Home,5.316667,4.950000
4,273198,884730,R2H0N8,SBGH,Other,Female,63.0,2014-09-27 12:32:00,2014-09-27 12:34:00,4,...,NaN,NaN,Physician,NaN,2014-09-27 18:47:00,1635.0,2014-09-27 18:59:00,ED Home,6.483333,6.250000

In [300]:
df_clean2.columns

Index(['Client.ID..Anonymized.', 'Client.Visit.ID..Anonymized.', 'postalcode',
       'EmergencyDepartment', 'ModeOfArrival', 'gender', 'Age.at.extract',
       'Point.of.Arrival', 'Triage.Start.Time', 'CTAS.Score',
       'EDComplaintCategory', 'EDChiefComplaint', 'Total.Lab.orders',
       'Total.LAB.Tests.ordered',
       'Average.Time.to.Perform.a.Lab.Order..Minutes.',
       'Total.Diagnostic.orders', 'Total.Diagnostics.Tests.ordered',
       'Average.Time.to.Perform.a.Diagnostics.Order..Minutes.',
       'provider.Type', 'Consult.Service', 'Initial.Assessment',
       'First.MD.Key', 'Last.contact.and.decision.to.discharge',
       'Disposition.Decision', 'LOS.Hours', 'Wait.Time.Hours'],
      dtype='object')

In [301]:
### Rename some of the columns for convenience:

df_clean2 = df_clean2.rename(columns={
                'Client.ID..Anonymized.': 'client_id',
                'Client.Visit.ID..Anonymized.' : 'visit_id',
                'postalcode': 'postal_code',
                'EmergencyDepartment' : 'ED',
                'ModeOfArrival' : 'arrival_mode',
                'Age.at.extract' : 'age',
                'Point.of.Arrival' : 'arrival_time',
                'Triage.Start.Time' : 'triage_time',
                'CTAS.Score' : 'CTAS',
                'EDComplaintCategory' : 'ED_complaint',
                'EDChiefComplaint' : 'chief_complaint',
                'Total.Lab.orders': 'tot_lab_orders',
                'Total.LAB.Tests.ordered': 'tot_lab_test_ordered',
                'Total.Diagnostic.orders': 'tot_diag_orders',
                'Total.Diagnostics.Tests.ordered': 'tot_diag_test_ordered',
                'Average.Time.to.Perform.a.Lab.Order..Minutes.': 'avg_lab_order_time_min',
                'Average.Time.to.Perform.a.Diagnostics.Order..Minutes.': 'avg_diag_order_time_min'
            })

In [302]:
df_clean2.head()

,client_id,visit_id,postal_code,ED,arrival_mode,gender,age,arrival_time,triage_time,CTAS,...,tot_diag_test_ordered,avg_diag_order_time_min,provider.Type,Consult.Service,Initial.Assessment,First.MD.Key,Last.contact.and.decision.to.discharge,Disposition.Decision,LOS.Hours,Wait.Time.Hours
0,246749,925668,R2L0J5,SBGH,Wheelchair,Male,90.0,2016-10-06 14:05:00,2016-10-06 14:07:00,4,...,2.0,22.0,Physician,GI Bleed Team,2016-10-06 21:06:00,198.0,2016-10-07 12:18:00,ED Home,22.216667,7.000000
1,141192,435664,R2M0M6,SBGH,Walking/Wheelchair/Other (walk-in),Female,57.0,2018-02-20 10:11:00,2018-02-20 10:13:00,3,...,1.0,2.0,Physician,NaN,2018-02-20 16:18:00,1590.0,2018-02-20 18:56:00,ED Home,8.766667,6.100000
2,141192,845811,R2M0M6,SBGH,Walking,Female,57.0,2017-01-26 10:50:00,2017-01-26 10:51:00,2,...,1.0,8.0,Physician,NaN,2017-01-26 15:27:00,1635.0,2017-01-26 16:55:00,Home,6.083333,4.616667
3,160336,670600,R2L0R8,HSC-A,Other,Female,40.0,2014-05-05 17:53:00,2014-05-05 17:59:00,2,...,NaN,NaN,Physician,NaN,2014-05-05 22:52:00,1919.0,2014-05-05 23:05:00,ED Home,5.316667,4.950000
4,273198,884730,R2H0N8,SBGH,Other,Female,63.0,2014-09-27 12:32:00,2014-09-27 12:34:00,4,...,NaN,NaN,Physician,NaN,2014-09-27 18:47:00,1635.0,2014-09-27 18:59:00,ED Home,6.483333,6.250000

#### Postal Code

In [303]:
print(f'Number of missing postal codes: {df_clean2['postal_code'].isnull().sum()}')

### There are missing values (That is, 'blanks').
### In addition to that, we have values such as: NA, CHINA, R3A0NA
### We keep all these records as they are for future use.

Number of missing postal codes: 12396

#### Emergency Department

In [304]:
print(f'Number of unique EDs: {df_clean2['ED'].nunique()}')

print(f'Number of missing values: {df_clean2['ED'].isnull().sum()}')

### There are only 4 EDs and NO missing values.

Number of unique EDs: 4
Number of missing values: 0

In [305]:
print(f'Number of patients in each {df_clean2['ED'].value_counts()}')

Number of patients in each ED
HSC-A    306741
HSC-P    267726
SBGH     214570
GH       145115
Name: count, dtype: int64

#### Arrival Model

In [306]:
print(f'Number of unique arrival modes: {df_clean2['arrival_mode'].nunique()}')

print(f'Number of missing values in arrival mode: {df_clean2['arrival_mode'].isnull().sum()}')

Number of unique arrival modes: 1866
Number of missing values in arrival mode: 1

In [307]:
### There is one record with a missing value in the arrival model. We will delete that record from further analysis.

df_clean2 = df_clean2.dropna(subset=['arrival_mode'])

The arrival model also contain categories such as 'Other' and 'Unknown'. Later we will regroup these records.

In [308]:
print(f'Number of records with arrival mode "Other": {len(df_clean2[df_clean2['arrival_mode']=='Other'])}')

Number of records with arrival mode "Other": 182026

In [309]:
print(f'Number of records with arrival mode "Unknown": {len(df_clean2[df_clean2['arrival_mode']=='Unknown'])}')

Number of records with arrival mode "Unknown": 82552

In [310]:
### Feature Engineering

In [311]:
### Optional replacement of numeric garbage codes
df_clean2["arrival_mode"] = df_clean2["arrival_mode"].replace({
    "78481": "Other",
    "102241": "Other",
    "10532": "Other"
})

In [312]:
print(f"Number of unique raw arrival modes: {df_clean2['arrival_mode'].nunique()}")

Number of unique raw arrival modes: 1866

In [313]:
### Step 1: Clean text in arrive mode (remove symbols, extra spaces)

In [314]:
### Function to clean text:

### Basic text cleaning
def clean_text_basic(x):
    if pd.isna(x):
        return x
    x = str(x).lower().strip()
    x = re.sub(r"[^a-z0-9\s]", " ", x)
    x = re.sub(r"\s+", " ", x).strip()
    return x

The function clean_text_basic standardizes and cleans text data by first handling missing values, then converting the input to lowercase and trimming extra spaces. It removes all special characters and punctuation, keeping only letters, numbers, and spaces, and finally replaces multiple spaces with a single space to ensure consistency. Overall, it prepares raw text into a clean, uniform format suitable for analysis or modeling.

In [315]:
df_clean2["arrival_mode_clean"] = df_clean2["arrival_mode"].apply(clean_text_basic)

In [316]:
### Step2: Word Order Normalization

In [317]:
def sort_words(x):
    if pd.isna(x):
        return x
    words = x.split()
    words_sorted = sorted(words)
    return " ".join(words_sorted)

The function sort_words standardizes text by first handling missing values, then splitting the input string into individual words, sorting those words alphabetically, and joining them back into a single string. This removes the effect of word order, so phrases with the same words but different arrangements (e.g., “chest pain severe” and “severe chest pain”) become identical, which can be useful for grouping or matching similar text entries.

In [318]:
df_clean2["arrival_mode_sorted"] = df_clean2["arrival_mode_clean"].apply(sort_words)

In [319]:
### Step 3: remove light stopwords

In [320]:
### Remove stopwords (noise words)

def remove_stopwords(x):
    if pd.isna(x):
        return x
    words = x.split()
    words = [w for w in words if w not in stopwords]
    return " ".join(words)

In [321]:
stopwords = {"and", "with", "from", "in", "to", "combined"}

In [322]:
df_clean2["arrival_mode_tokens"] = df_clean2["arrival_mode_sorted"].apply(remove_stopwords)

In [323]:
### Check cleaned value counts for manual review
vc = df_clean2["arrival_mode_tokens"].value_counts(dropna=False)
vc_df = vc.reset_index()
vc_df.columns = ["text", "count"]

In [324]:
### Step 4: final categorization

In [325]:
def categorize_arrival_mode(x):
    if pd.isna(x):
        return "Unknown"
    
    x = str(x).lower().strip()
    words = set(x.split())

    # explicit unknown
    if x in {"unknown", "unk", ""}:
        return "Unknown"

    # air transport first
    if any(w in words for w in [
        "air", "helicopter", "flight", "lifeflight", "stars", "sky", "nurse", "rn"
    ]):
        return "Air Transport"

    # police next
    if "police" in words:
        return "Police"

    # EMS / ambulance
    if any(w in words for w in [
        "ems", "ambulance", "municipal", "rural", "external", "local", "perimeter"
    ]):
        return "EMS"

    # stretcher
    if "stretcher" in words:
        return "Stretcher"

    # wheelchair and similar assisted mobility
    if any(w in words for w in [
        "wheelchair", "walker", "cane", "crutches", "stroller"
    ]):
        return "Wheelchair"

    # walk-in
    if any(w in words for w in [
        "walk", "walking"
    ]):
        return "Walk-in"

    # private / non-EMS transport
    if any(w in words for w in [
        "car", "taxi", "staxi", "bus"
    ]):
        return "Walk-in"

    # carried patients tend to be non-ambulatory
    if "carried" in words:
        return "Stretcher"

    return "Other"

In [326]:
df_clean2["arrival_mode_final"] = df_clean2["arrival_mode_tokens"].apply(categorize_arrival_mode)

In [327]:
### Drop unnecessary columns
df_clean2 = df_clean2.drop(columns=[
    "arrival_mode_clean",
    "arrival_mode_sorted",
    "arrival_mode_tokens",
    "arrival_mode"
])

In [328]:
### Rename columns:
df_clean2 = df_clean2.rename(columns={
    'arrival_mode_final': 'arrival_mode'
})

In [329]:
print(df_clean2["arrival_mode"].value_counts())

arrival_mode
Walk-in          327601
Other            182908
EMS              148750
Wheelchair       112711
Unknown           82553
Stretcher         62765
Air Transport     10840
Police             6023
Name: count, dtype: int64

#### Gender

In [330]:
### Unique types:
print(f'Gender types: {df_clean2['gender'].unique()}')

### How many observations under each category:
print(f'Observations under each {df_clean2['gender'].value_counts()}')

Gender types: ['Male' 'Female' 'Undifferentiate' 'Unknown']
Observations under each gender
Female             481322
Male               452739
Unknown                71
Undifferentiate        19
Name: count, dtype: int64

In [331]:
### Change both Unknown and Undifferentiate to "Other".

df_clean2['gender'] = (
    df_clean2['gender']
    .astype('category')  # ensure it's categorical
    .cat.rename_categories(lambda x: 'Other' if x in ('Unknown', 'Undifferentiated') else x)
)

#### Age

In [332]:
### Are there any missing values in the age?
print(f'Number of missing values in age: {df_clean2['age'].isnull().sum()}')

Number of missing values in age: 2

In [333]:
### Delete the records with missing values in age.

df_clean2 = df_clean2.dropna(subset=['age'])

In [334]:
### Summary Statistics:

df_clean2['age'].describe()

count    934149.000000
mean         43.724501
std          26.166428
min           5.000000
25%          21.000000
50%          40.000000
75%          64.000000
max         173.000000
Name: age, dtype: float64

**Note:** According to the current data set, the maximum age is 173. This is unrealistic. Thus, we will remove records with an age of 173.

In [335]:
df_clean2 = df_clean2[~df_clean2['age'].isin([173])]

In [336]:
df_clean2['age'].describe()

count    934134.000000
mean         43.722425
std          26.161510
min           5.000000
25%          21.000000
50%          40.000000
75%          64.000000
max         123.000000
Name: age, dtype: float64

#### Arrival Time

In [337]:
### Are there any missing values?
print(f'Number of missing values in arrival time: {df_clean2['arrival_time'].isnull().sum()}')

### There are NO missing values.

Number of missing values in arrival time: 0

In [338]:
### Summary of arrival time:

print("Earliest arrival time    :", df_clean2['arrival_time'].min())
print("Latest arrival time      :", df_clean2['arrival_time'].max())
print("Date Range  :", df_clean2['arrival_time'].max() - df_clean2['arrival_time'].min())

Earliest arrival time    : 2011-12-29 15:21:00
Latest arrival time      : 2018-05-30 23:59:00
Date Range  : 2344 days 08:38:00

**Notes**:

The Wait Time is the initial assessment minus the triage time:

**wait time = initial assessment time - triage time**

The length of Stay (LOS) is the last contact time minus the arrival time:

**LOS = last contact time - arrival time**

Thus, if there are some missing values in triage time, we can recover the missing values using wait time and initial assessment time. If both wait time and initial assessment time are missing, we will make triage time equal to arrival time.

Similarly, if there are missing values in the last contact time, we can recover them using LOS and arrival time.

In [339]:
### Rename relevant columns for convenience:

df_clean2 = df_clean2.rename(columns={
                'Initial.Assessment': 'init_assess_time',
                'Last.contact.and.decision.to.discharge' : 'last_contact_time',
                'LOS.Hours' : 'LOS_Hr',
                'Wait.Time.Hours' : 'wait_time_Hr'
            })

Based on the formulas of wait time and LOS, we expect the following inequalities:

arrival time < triage time < initial assessment time < last contact time

wait time < LOS

In practice, these inequalities do NOT always hold, due to:

- Data entry errors
- System recording differences
- Missing + reconstructed values
- Workflow edge cases

Moreover, the above definition of wait time is correct if we define the wait time as the time from triage to physician assessment.
However, if we instead want the total waiting time from arrival, it would be: Wait time = initial assessment time − arrival time

In [340]:
### Check whether there are any cases with triage time < arrival time:

print(f'Number of records with triage time < arrival time: {len(df_clean2[df_clean2['triage_time']<df_clean2['arrival_time']])}')

Number of records with triage time < arrival time: 7

In practice, there is a possibility of observing triage time < arrival time. When a patient arrived in "Ambulance - air and ground", they started the triage on the way. Thus, the arrival time is greater than the triage time.

Therefore, we will keep these records for further analysis.

In [341]:
### Check whether there are any cases with initial assessment time < triage time:

print(f'Number of records with initial assessment time < triage time: {len(df_clean2[df_clean2['init_assess_time']<df_clean2['triage_time']])}')

Number of records with initial assessment time < triage time: 898

In practice, there is a possibility of observing initial assessment time < triage time.

- Immediate/critical care (Patient arrives in critical condition)
- Delayed data entry
- Different definitions across systems
- Clock/system inconsistencies

Thus, we will keep these records for further analysis.

In [342]:
### Check whether there are any cases with last contact time < initial assessment time:

print(f'Number of records with last contact time < initial assessment time: {len(df_clean2[df_clean2['last_contact_time']<df_clean2['init_assess_time']])}')

Number of records with last contact time < initial assessment time: 13324

"last contact time < initial assessment time" is not realistic. Thus we will remove these records from further analysis.

In [343]:
df_clean2 = df_clean2[~(df_clean2['last_contact_time'] < df_clean2['init_assess_time'])]

Depending on the definition, there are multiple ways to calculate wait time:
    
- initial assessment time − arrival time
- initial assessment time - triage time

In the data set, we have wait_time_Hr. First, we need to identify which formula they have used to calculate wait time.

In [344]:
pd.DataFrame({
    'wait_time_Hr': pd.to_timedelta(df_clean2['wait_time_Hr'], unit='h'),
    'computed_wait_time': df_clean2['init_assess_time'] - df_clean2['arrival_time']
}).head(5)

               wait_time_Hr computed_wait_time
0           0 days 07:00:00    0 days 07:01:00
1           0 days 06:06:00    0 days 06:07:00
2 0 days 04:37:00.000001200    0 days 04:37:00
3           0 days 04:57:00    0 days 04:59:00
4           0 days 06:15:00    0 days 06:15:00

In [345]:
pd.DataFrame({
    'wait_time_Hr': pd.to_timedelta(df_clean2['wait_time_Hr'], unit='h'),
    'computed_wait_time': df_clean2['init_assess_time'] - df_clean2['triage_time']
}).head(5)

               wait_time_Hr computed_wait_time
0           0 days 07:00:00    0 days 06:59:00
1           0 days 06:06:00    0 days 06:05:00
2 0 days 04:37:00.000001200    0 days 04:36:00
3           0 days 04:57:00    0 days 04:53:00
4           0 days 06:15:00    0 days 06:13:00

Since it would be hard to see which approach gives the closest values, we try the following approach:

In [346]:
# Compute differences in hours
diff_arrival = (df_clean2['init_assess_time'] - df_clean2['arrival_time']).dt.total_seconds() / 3600
diff_triage  = (df_clean2['init_assess_time'] - df_clean2['triage_time']).dt.total_seconds() / 3600

# Error vs wait_time_Hr
error_arrival = (diff_arrival - df_clean2['wait_time_Hr']).abs()
error_triage  = (diff_triage  - df_clean2['wait_time_Hr']).abs()

print(f"Arrival formula  — Mean error: {error_arrival.mean():.4f} hrs, Max error: {error_arrival.max():.4f} hrs")
print(f"Triage formula   — Mean error: {error_triage.mean():.4f} hrs, Max error: {error_triage.max():.4f} hrs")

Arrival formula  — Mean error: 0.1264 hrs, Max error: 528.2000 hrs
Triage formula   — Mean error: 0.2384 hrs, Max error: 33286.8333 hrs

Thus, based on the mean and maximum error, it is safe to assume wait_time_Hr in the data set is calculated as follows:

wait time = initial assessment time - arrival time

In [347]:
print(f'Number of missing values in wait_time_Hr: {df_clean2['wait_time_Hr'].isnull().sum()}')

Number of missing values in wait_time_Hr: 112

In [348]:
print(f'Number of missing values in initial assessment time: {df_clean2['init_assess_time'].isnull().sum()}')

Number of missing values in initial assessment time: 183816

Note: Since there are NO missing values in the arrival time, we should be able to calculate most of the missing values in wait_time and init_assess_time using the wait time formula.

In [349]:
# Case 1: init_assess_time is missing but wait_time_Hr is available → compute init_assess_time
mask1 = df_clean2['init_assess_time'].isna() & df_clean2['wait_time_Hr'].notna()
df_clean2.loc[mask1, 'init_assess_time'] = (
    df_clean2.loc[mask1, 'arrival_time'] + 
    pd.to_timedelta(df_clean2.loc[mask1, 'wait_time_Hr'], unit='h')
)

# Case 2: wait_time_Hr is missing but init_assess_time is available → compute wait_time_Hr
mask2 = df_clean2['wait_time_Hr'].isna() & df_clean2['init_assess_time'].notna()
df_clean2.loc[mask2, 'wait_time_Hr'] = (
    (df_clean2.loc[mask2, 'init_assess_time'] - df_clean2.loc[mask2, 'arrival_time'])
    .dt.total_seconds() / 3600
)

# Case 3: both missing → leave as is (nothing to do)

Now we will focus on LOS_Hr and last_contact_time

In [350]:
print(f'Number of missing values in LOS_Hr: {df_clean2['LOS_Hr'].isnull().sum()}')

Number of missing values in LOS_Hr: 6

In [351]:
print(f'Number of missing values in last_contact_time: {df_clean2['last_contact_time'].isnull().sum()}')

Number of missing values in last_contact_time: 49

The missing values can be computed using the LOS formular.

In [352]:
# Case 1: last_contact_time is missing but LOS_Hr is available → compute last_contact_time
mask1 = df_clean2['last_contact_time'].isna() & df_clean2['LOS_Hr'].notna()
df_clean2.loc[mask1, 'last_contact_time'] = (
    df_clean2.loc[mask1, 'arrival_time'] + 
    pd.to_timedelta(df_clean2.loc[mask1, 'LOS_Hr'], unit='h')
)

# Case 2: LOS_Hr is missing but last_contact_time is available → compute LOS_Hr
mask2 = df_clean2['LOS_Hr'].isna() & df_clean2['last_contact_time'].notna()
df_clean2.loc[mask2, 'LOS_Hr'] = (
    (df_clean2.loc[mask2, 'last_contact_time'] - df_clean2.loc[mask2, 'arrival_time'])
    .dt.total_seconds() / 3600
)

# Case 3: both missing → leave as is

#### Triage Time

In [353]:
### Are there any missing values?
print(df_clean2['triage_time'].isnull().sum())

2711

Since these missing values do not directly impact our analysis, we keep them for further analysis.

In [354]:
### Summary of triage time:

print("Earliest    :", df_clean2['triage_time'].min())
print("Latest      :", df_clean2['triage_time'].max())

Earliest    : 2011-12-29 15:23:00
Latest      : 2018-05-31 00:20:00

#### CTAS Score

In [355]:
### Are there any missing values?
print(f'Number of missing values in CTAS: {df_clean2['CTAS'].isnull().sum()}')

### What are the unique categories:
print(f'Number of unique values in CTAS: {df_clean2['CTAS'].nunique()}')

### How many observations under each category?
print(f'Number of observations in each {df_clean2['CTAS'].value_counts()}')

Number of missing values in CTAS: 0
Number of unique values in CTAS: 6
Number of observations in each CTAS
3          339165
4          305951
2          146584
5          106426
1           14027
UNKNOWN      8657
Name: count, dtype: int64

**Note:**

CTAS is one of the important features to determine treatment priority based on the urgency of conditions.
It also helps in predicting necessary resources and wait times. It is important to check the records with the existing CATS score.

Thus, we will remove the records with 'UNKNOWN' CTAS scores from further analysis.

In [356]:
df_clean2 = df_clean2[~df_clean2['CTAS'].isin(['UNKNOWN'])]

The next variable of interest is complaints.
There are two variables under this: ED complaint category (ED_complaint) & ED chief complaint (chief_complaint).

#### ED Complaint

In [357]:
print(f'Number of missing values in ED_complaint: {df_clean2['ED_complaint'].isnull().sum()}')

Number of missing values in ED_complaint: 111

In [358]:
### In the original data set, for some patients, ED_complaint is 'UNKNOWN'.
### Let's check how many patients are there with ED_complaint UNKNOWN.

print(f'Number of UNKNOWN in ED_complaint: {(len(df_clean2[df_clean2['ED_complaint']=='UNKNOWN']))}')

Number of UNKNOWN in ED_complaint: 124

In [359]:
print(f'Number of unique categories in ED_complaint: {df_clean2['ED_complaint'].nunique()}')

### There are 22 unique categories in Ed_complaint

Number of unique categories in ED_complaint: 23

In [360]:
### How many recorded patients under each ED_complaint category:

print(df_clean2['ED_complaint'].value_counts())

ED_complaint
ETRIAGE                      230565
Cardiovascular               102690
Gastrointestinal             100896
Orthopedic                    81732
Neurologic                    67673
Skin                          59452
Respiratory                   55914
General and Minor             37735
Genitourinary                 29946
Mental Health                 26400
General & Minor               20904
Trauma                        18624
OBGYN                         14103
Substance Misuse              13478
ENT - Mouth, Throat, Neck     12756
OB-GYN                         8758
ENT - Mouth/Throat/Neck        6950
Ophthalmology                  6487
Substance misuse               5989
ENT - Nose                     5326
ENT - Ears                     4290
Environmental                  1250
UNKNOWN                         124
Name: count, dtype: int64

Note:

ETRIAGE usually means:

- complaint entered via triage system
- not mapped to a clinical category
- placeholder or default coding

In [361]:
### Fix ED_complaint missing values and "UNKNOWN".

### Rename 'UNKNOWN' → 'unknown'
df_clean2['ED_complaint'] = df_clean2['ED_complaint'].replace({'UNKNOWN': 'unknown'})

### Fill NaN with 'unknown'
df_clean2['ED_complaint'] = df_clean2['ED_complaint'].fillna('unknown')

In [362]:
def categorize_ed_complaint(x):
    if pd.isna(x):
        return "unknown"
    
    x = str(x).lower().strip()

    # normalize symbols
    x = x.replace("&", "and")

    # unknown stays as is
    if x in ["unknown", ""]:
        return "unknown"

    # ETRIAGE stays separate
    if "etriag" in x:
        return "ETRIAGE"

    # General
    if "general" in x or "minor" in x:
        return "General_Minor"

    # Cardiovascular
    if "cardio" in x:
        return "Cardiovascular"

    # Gastrointestinal
    if "gastro" in x:
        return "Gastrointestinal"

    # Orthopedic
    if "ortho" in x:
        return "Orthopedic"

    # Neurologic
    if "neuro" in x:
        return "Neurologic"

    # Respiratory
    if "respir" in x:
        return "Respiratory"

    # Mental Health
    if "mental" in x:
        return "Mental_Health"

    # Substance Misuse
    if "substance" in x:
        return "Substance_Misuse"

    # Trauma
    if "trauma" in x:
        return "Trauma"

    # OB-GYN
    if "obgyn" in x or "ob-gyn" in x:
        return "OBGYN"

    # ENT (all subtypes)
    if "ent" in x:
        return "ENT"

    return "Other"

In [363]:
df_clean2["ED_complaint_final"] = df_clean2["ED_complaint"].apply(categorize_ed_complaint)

In [364]:
df_clean2["ED_complaint_final"].value_counts()

ED_complaint_final
ETRIAGE             230565
Cardiovascular      102690
Gastrointestinal    100896
Other                95885
Orthopedic           81732
Neurologic           67673
General_Minor        58639
Respiratory          55914
ENT                  29322
Mental_Health        27650
OBGYN                22861
Substance_Misuse     19467
Trauma               18624
unknown                235
Name: count, dtype: int64

In [365]:
### Drop unnecessary column:
df_clean2 = df_clean2.drop(columns=["ED_complaint"])

In [366]:
### Rename columns:
df_clean2 = df_clean2.rename(columns={
    'ED_complaint_final': 'ED_complaint'
})

#### Chief Complaint

In [367]:
print(f'Number of missing values in chief_complaint: {df_clean2['chief_complaint'].isnull().sum()}')

Number of missing values in chief_complaint: 111

In [368]:
print(f'Number of UNKNOWN in chief_complaint: {len(df_clean2[df_clean2['chief_complaint']=='UNKNOWN'])}')

Number of UNKNOWN in chief_complaint: 124

In [369]:
print(f'Number of unique categories in chief_complaint: {df_clean2['chief_complaint'].nunique()}')

Number of unique categories in chief_complaint: 294

In [370]:
### Before cleaning text and simplifying the number of categories, we change both missing values and UNKNOWN to "unknown".
df_clean2["chief_complaint"] = df_clean2["chief_complaint"].fillna("unknown")
df_clean2["chief_complaint"] = df_clean2["chief_complaint"].replace("UNKNOWN", "unknown")

In [371]:
### Feature Engineering

In [372]:
### Step 1: Clean the text

In [373]:
def clean_chief_complaint(x):
    if pd.isna(x):
        return x
    x = str(x).lower().strip()
    x = re.sub(r"[^a-z0-9\s]", " ", x)
    x = re.sub(r"\s+", " ", x).strip()
    return x

In [374]:
df_clean2["chief_complaint_clean"] = df_clean2["chief_complaint"].apply(clean_chief_complaint)

In [375]:
print(f'Number of unique chief complaints: {df_clean2['chief_complaint_clean'].nunique()}')

Number of unique chief complaints: 258

In [376]:
### Step 2: Normalize Common Variations

In [377]:
mapping = {
    "abd pain": "abdominal pain",
    "abdo pain": "abdominal pain",
    "sob": "shortness of breath",
    "cp": "chest pain",
    "n v": "nausea vomiting"
}

In [378]:
df_clean2["chief_complaint_clean"] = df_clean2["chief_complaint_clean"].replace(mapping)

In [379]:
### Step 3: Create Category Mapping Function

In [380]:
def map_chief_complaint(x):
    if pd.isna(x):
        return "other"
    
    # cardiac
    if "chest pain" in x:
        return "cardiac"
    
    # respiratory
    if any(k in x for k in ["breath", "cough", "asthma"]):
        return "respiratory"
    
    # GI
    if any(k in x for k in ["abdominal", "nausea", "vomit", "diarrhea"]):
        return "gastrointestinal"
    
    # neuro
    if any(k in x for k in ["headache", "dizzy", "seizure", "syncope"]):
        return "neurological"
    
    # trauma
    if any(k in x for k in ["fall", "injury", "fracture", "trauma"]):
        return "trauma"
    
    # infection
    if "fever" in x:
        return "infection"
    
    # musculoskeletal
    if any(k in x for k in ["back pain", "joint", "leg pain"]):
        return "musculoskeletal"
    
    # skin
    if any(k in x for k in ["rash", "wound", "cut"]):
        return "skin"
    
    # mental
    if any(k in x for k in ["anxiety", "depression"]):
        return "mental_health"
    
    # general
    if any(k in x for k in ["weakness", "fatigue", "unwell"]):
        return "general"
    
    # unknown
    if x == "unknown":
        return "unknown"
    
    return "other"

In [381]:
### Step 4: Apply

In [382]:
df_clean2["chief_complaint_final"] = df_clean2["chief_complaint_clean"].apply(map_chief_complaint)

In [383]:
df_clean2['chief_complaint_final'].value_counts()

chief_complaint_final
other               366777
trauma              132265
gastrointestinal    115539
respiratory          83012
cardiac              56442
neurological         38383
infection            36242
general              29230
skin                 19318
musculoskeletal      18089
mental_health        16621
unknown                235
Name: count, dtype: int64

In [384]:
### Drop unnecessary columns
df_clean2 = df_clean2.drop(columns=["chief_complaint_clean","chief_complaint"])

In [385]:
### Rename columns:
df_clean2 = df_clean2.rename(columns={
    'chief_complaint_final': 'chief_complaint'
})

#### Disposition

The next variable of interest is 'Disposition.Decision'. We will rename it as 'disposition'

In [386]:
df_clean2 = df_clean2.rename(columns={
                'Disposition.Decision': 'disposition'
            })

In [387]:
print(f'Number of missing values in disposition: {df_clean2['disposition'].isnull().sum()}')

Number of missing values in disposition: 0

In [388]:
print(f'Number of unique categories in disposition: {df_clean2['disposition'].nunique()}')

Number of unique categories in disposition: 23

In [389]:
df_clean2['disposition'].value_counts()

disposition
ED Home                           667659
ED TRSF to IP                     119566
ED Reg/Triaged LWBS                48184
Home                               40069
ED TRSF to Ext Acute Care/ER        6713
ED TRSF to Internal Clinic          5725
ED Reg LWBS                         5491
ED Reg/Triaged/Assess LWBS          3758
ED Home with Support Services       2962
ED Reg/Triaged/Assess LAMA          2916
TRSF to Other Facility              2073
ED TRSF to Internal DNC             2005
ED TRSF to Ext Non Acute Care       1860
ED Death after Arrival               716
TRSF to Continuing Care              578
ED TRSF to Internal ER               460
Left Against Medical Advice          420
TRSF to Acute Care                   369
Deceased                             357
Home with Support Services           131
ED TRSF to IP Critical Care/OR       110
ED Death on Arrival                   25
No Return from Pass                    6
Name: count, dtype: int64

In [390]:
### Dataset after initial cleaning:

df_clean2.info()

<class 'pandas.core.frame.DataFrame'>
Index: 912153 entries, 0 to 934151
Data columns (total 26 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   client_id                912153 non-null  int64
 1   visit_id                 912153 non-null  int64
 2   postal_code              900180 non-null  object
 3   ED                       912153 non-null  object
 4   gender                   912153 non-null  category
 5   age                      912153 non-null  float64
 6   arrival_time             912153 non-null  datetime64[ns]
 7   triage_time              911996 non-null  datetime64[ns]
 8   CTAS                     912153 non-null  object
 9   tot_lab_orders           469845 non-null  float64
 10  tot_lab_test_ordered     469845 non-null  float64
 11  avg_lab_order_time_min   440460 non-null  float64
 12  tot_diag_orders          309942 non-null  float64
 13  tot_diag_test_ordered    309942 non-null  float64
 14  avg_diag_order_time_min  297359 non-null  float64
 15  provider.Type            735330 non-null  object
 16  Consult.Service          192546 non-null  object
 17  init_assess_time         912046 non-null  datetime64[ns]
 18  First.MD.Key             735330 non-null  float64
 19  last_contact_time        912153 non-null  datetime64[ns]
 20  disposition              912153 non-null  object
 21  LOS_Hr                   912153 non-null  float64
 22  wait_time_Hr             912046 non-null  float64
 23  arrival_mode             912153 non-null  object
 24  ED_complaint             912153 non-null  object
 25  chief_complaint          912153 non-null  object
dtypes: category(1), datetime64[ns](4), float64(10), int64(2), object(9)
memory usage: 181.8+ MB

Patient Attributes:

These are attributes directly related to the patient. This includes:

- arrival mode
- gender
- age
- CTAS
- chief complaint
- previous visits (number of previous visits to ED)


System Attributes:

These are attributes directly related to the system (not directly related to the patient). This includes:

- emergency department: ED
- period of day (NOT available in the data, but can be calculated): period_of_day
- day of week (NOT available in the data, but can be calculated): day_of_week
- period of the year (NOT available in the data, but can be calculated): season
- holiday/not a holiday (NOT available in the data, but can be calculated): holiday
- ED complaint

In [391]:
### Make a copy of the data set before computing new attributes
df_clean3 = df_clean2.copy()

#### System Attributes

In [392]:
### Sort by arrival_time first

df_clean3 = df_clean3.sort_values('arrival_time')

In [393]:
### Period of Day
# Morning: 6:00 - 11:59, Afternoon: 12:00 - 17:59, Evening: 18:00 - 21:59, Night: 22:00 - 5:59

def get_period_of_day(hour):
    if 6 <= hour < 12:
        return 'Morning'
    elif 12 <= hour < 18:
        return 'Afternoon'
    elif 18 <= hour < 22:
        return 'Evening'
    else:
        return 'Night'

In [394]:
df_clean3['period_of_day'] = df_clean3['arrival_time'].dt.hour.map(get_period_of_day)

In [395]:
### Day of Week
### e.g. 'Monday', 'Tuesday'

df_clean3['day_of_week'] = df_clean3['arrival_time'].dt.day_name()

In [396]:
### Season (Manitoba - Northern Hemisphere) ---
### Winter: Dec-Feb, Spring: Mar-May, Summer: Jun-Aug, Fall: Sep-Nov

def get_season(month):
    if month in [12, 1, 2]:
        return 'Winter'
    elif month in [3, 4, 5]:
        return 'Spring'
    elif month in [6, 7, 8]:
        return 'Summer'
    else:
        return 'Fall'

In [397]:
df_clean3['season'] = df_clean3['arrival_time'].dt.month.map(get_season)

In [398]:
### Holiday (Manitoba)
### Get the range of years in the data to cover all holidays

years = df_clean3['arrival_time'].dt.year.dropna().unique().astype(int).tolist()
mb_holidays = holidays.Canada(prov='MB', years=years)

In [399]:
df_clean3['holiday'] = df_clean3['arrival_time'].dt.date.map(
    lambda x: 'Holiday' if x in mb_holidays else 'Not Holiday'
)

We are interested in two quantities at triage: **expected service time** and **probability of admission**

First, we will investigate "expected service time".

**service_time = last contact time − initial assessment time**

In [400]:
df_clean3['service_time'] = df_clean3['last_contact_time'] - df_clean3['init_assess_time']

In [401]:
### Summary Statistics: service time
df_clean3['service_time'].describe()

count                       912046
mean     0 days 03:47:04.274784385
std      0 days 12:07:14.637784955
min      -14 days +04:19:00.000120
25%                0 days 00:24:00
50%      0 days 01:26:59.999998800
75%                0 days 03:58:00
max              345 days 01:51:00
Name: service_time, dtype: object

In [402]:
### Note that most models would not be able to handle timedelta64[ns] service_time. Thus, we will convert it to minutes.
df_clean3['service_time_min'] = df_clean3['service_time'].dt.total_seconds() / 60

In [403]:
df_clean3['service_time_min'].describe()

count    912046.000000
mean        227.071246
std         727.243963
min      -19900.999998
25%          24.000000
50%          87.000000
75%         238.000000
max      496911.000000
Name: service_time_min, dtype: float64

We can see that there are some negative values and extremely large values.

#### Number of Previous Visits

Remember that we have client_id and visit_id in the data. For each client, there could be several visit_ids, indicating multiple visits to the ED. Thus, in each case, we can add a variable to indicate the number of previous visits.

In [404]:
df_clean3.sort_values(
    by=['client_id', 'arrival_time'],
    ascending=[True, True]  # control direction per column
).head(10)

,client_id,visit_id,postal_code,ED,gender,age,arrival_time,triage_time,CTAS,tot_lab_orders,...,wait_time_Hr,arrival_mode,ED_complaint,chief_complaint,period_of_day,day_of_week,season,holiday,service_time,service_time_min
681146,1,736092,R2K1Z6,HSC-A,Male,55.0,2014-03-01 20:00:00,2014-03-01 20:03:00,4,2.0,...,6.150000,Other,General_Minor,other,Evening,Saturday,Spring,Not Holiday,0 days 02:25:00,145.0
190090,1,899319,R2K1Z6,SBGH,Male,55.0,2015-01-27 14:01:00,2015-01-27 14:02:00,3,10.0,...,0.316667,Other,Respiratory,respiratory,Afternoon,Tuesday,Winter,Not Holiday,1 days 01:25:00,1525.0
897311,1,102014,R2K1Z6,HSC-A,Male,55.0,2016-11-18 22:28:00,2016-11-18 22:29:00,2,12.0,...,3.516667,Police,Mental_Health,other,Night,Friday,Fall,Not Holiday,3 days 19:31:00,5491.0
150217,1,884946,R2K1Z6,SBGH,Male,55.0,2018-03-14 23:33:00,2018-03-14 23:40:00,3,14.0,...,2.016667,Wheelchair,Neurologic,neurological,Night,Wednesday,Spring,Not Holiday,0 days 17:23:00,1043.0
643134,2,7482,R0B1P0,HSC-A,Female,64.0,2013-07-22 09:07:00,2013-07-22 09:15:00,5,NaN,...,1.283333,Other,ENT,other,Morning,Monday,Summer,Not Holiday,0 days 00:13:00,13.0
580703,3,578521,R3M0S6,HSC-P,Female,10.0,2018-05-29 18:51:00,2018-05-29 18:54:00,3,NaN,...,0.850000,Wheelchair,Orthopedic,trauma,Evening,Tuesday,Spring,Not Holiday,0 days 00:10:00,10.0
525695,4,612977,R2G2J9,HSC-P,Female,11.0,2013-06-25 06:14:00,2013-06-25 06:14:00,3,2.0,...,1.550000,Unknown,ETRIAGE,infection,Morning,Tuesday,Summer,Not Holiday,0 days 02:12:00,132.0
131379,4,906303,R2W3N4,HSC-P,Female,11.0,2013-11-10 21:26:00,2013-11-10 21:26:00,2,NaN,...,0.100000,Unknown,ETRIAGE,infection,Evening,Sunday,Fall,Not Holiday,0 days 02:17:00,137.0
266476,4,757655,R2W3N4,HSC-P,Female,11.0,2014-01-07 16:30:00,2014-01-07 16:30:00,3,NaN,...,0.300000,Unknown,ETRIAGE,respiratory,Afternoon,Tuesday,Winter,Not Holiday,0 days 01:03:00,63.0
418053,4,753947,R2W1Z2,HSC-P,Female,11.0,2017-12-16 12:52:00,2017-12-16 13:19:00,4,NaN,...,2.900000,Wheelchair,ENT,other,Afternoon,Saturday,Winter,Not Holiday,0 days 00:01:00,1.0

In [405]:
# Sort by client_id and arrival_time to establish visit order
df_temp = df_clean3[['client_id', 'visit_id', 'arrival_time']].copy()
df_temp = df_temp.sort_values(['client_id', 'arrival_time'])

# Rank visits within each client group (0-indexed = number of previous visits)
df_temp['previous_visits'] = df_temp.groupby('client_id', observed=True).cumcount()
df_temp['previous_visits'] = df_temp['previous_visits'].astype('Int64')

# Merge previous_visits into df_clean3
df_clean4 = df_clean3.merge(
    df_temp[['visit_id', 'previous_visits']],
    on='visit_id',
    how='left'
)

In [406]:
df_clean4.sort_values(
    by=['client_id', 'arrival_time'],
    ascending=[True, True]  # control direction per column
).head(10)

,client_id,visit_id,postal_code,ED,gender,age,arrival_time,triage_time,CTAS,tot_lab_orders,...,arrival_mode,ED_complaint,chief_complaint,period_of_day,day_of_week,season,holiday,service_time,service_time_min,previous_visits
144008,1,736092,R2K1Z6,HSC-A,Male,55.0,2014-03-01 20:00:00,2014-03-01 20:03:00,4,2.0,...,Other,General_Minor,other,Evening,Saturday,Spring,Not Holiday,0 days 02:25:00,145.0,0
296313,1,899319,R2K1Z6,SBGH,Male,55.0,2015-01-27 14:01:00,2015-01-27 14:02:00,3,10.0,...,Other,Respiratory,respiratory,Afternoon,Tuesday,Winter,Not Holiday,1 days 01:25:00,1525.0,1
614325,1,102014,R2K1Z6,HSC-A,Male,55.0,2016-11-18 22:28:00,2016-11-18 22:29:00,2,12.0,...,Police,Mental_Health,other,Night,Friday,Fall,Not Holiday,3 days 19:31:00,5491.0,2
868765,1,884946,R2K1Z6,SBGH,Male,55.0,2018-03-14 23:33:00,2018-03-14 23:40:00,3,14.0,...,Wheelchair,Neurologic,neurological,Night,Wednesday,Spring,Not Holiday,0 days 17:23:00,1043.0,3
49300,2,7482,R0B1P0,HSC-A,Female,64.0,2013-07-22 09:07:00,2013-07-22 09:15:00,5,NaN,...,Other,ENT,other,Morning,Monday,Summer,Not Holiday,0 days 00:13:00,13.0,0
911451,3,578521,R3M0S6,HSC-P,Female,10.0,2018-05-29 18:51:00,2018-05-29 18:54:00,3,NaN,...,Wheelchair,Orthopedic,trauma,Evening,Tuesday,Spring,Not Holiday,0 days 00:10:00,10.0,0
37523,4,612977,R2G2J9,HSC-P,Female,11.0,2013-06-25 06:14:00,2013-06-25 06:14:00,3,2.0,...,Unknown,ETRIAGE,infection,Morning,Tuesday,Summer,Not Holiday,0 days 02:12:00,132.0,0
97627,4,906303,R2W3N4,HSC-P,Female,11.0,2013-11-10 21:26:00,2013-11-10 21:26:00,2,NaN,...,Unknown,ETRIAGE,infection,Evening,Sunday,Fall,Not Holiday,0 days 02:17:00,137.0,1
121345,4,757655,R2W3N4,HSC-P,Female,11.0,2014-01-07 16:30:00,2014-01-07 16:30:00,3,NaN,...,Unknown,ETRIAGE,respiratory,Afternoon,Tuesday,Winter,Not Holiday,0 days 01:03:00,63.0,2
819576,4,753947,R2W1Z2,HSC-P,Female,11.0,2017-12-16 12:52:00,2017-12-16 13:19:00,4,NaN,...,Wheelchair,ENT,other,Afternoon,Saturday,Winter,Not Holiday,0 days 00:01:00,1.0,3

#### Disposition

In [407]:
### Note: disposition has no missing values.
df_clean4['disposition'].value_counts()

disposition
ED Home                           667659
ED TRSF to IP                     119566
ED Reg/Triaged LWBS                48184
Home                               40069
ED TRSF to Ext Acute Care/ER        6713
ED TRSF to Internal Clinic          5725
ED Reg LWBS                         5491
ED Reg/Triaged/Assess LWBS          3758
ED Home with Support Services       2962
ED Reg/Triaged/Assess LAMA          2916
TRSF to Other Facility              2073
ED TRSF to Internal DNC             2005
ED TRSF to Ext Non Acute Care       1860
ED Death after Arrival               716
TRSF to Continuing Care              578
ED TRSF to Internal ER               460
Left Against Medical Advice          420
TRSF to Acute Care                   369
Deceased                             357
Home with Support Services           131
ED TRSF to IP Critical Care/OR       110
ED Death on Arrival                   25
No Return from Pass                    6
Name: count, dtype: int64

In [408]:
df_clean4['disposition'].nunique()

23

In [409]:
### Define death categories (to remove)
death_categories = [
    'Deceased',
    'ED Death after Arrival',
    'ED Death on Arrival'
]

In [410]:
### Remove them from the dataset
df_clean4 = df_clean4[~df_clean4['disposition'].isin(death_categories)].copy()

In [411]:
### Classification Logic

admitted_categories = [
    'ED TRSF to IP',
    'ED TRSF to IP Critical Care/OR',
    'TRSF to Acute Care',
    'ED TRSF to Internal ER',
    'ED TRSF to Ext Acute Care/ER',
    'TRSF to Other Facility',

    'ED TRSF to Internal Clinic',
    'ED TRSF to Internal DNC',
    'ED TRSF to Ext Non Acute Care',
    'TRSF to Continuing Care'
]

not_admitted_categories = [
    'ED Home',
    'Home',
    'Home with Support Services',
    'ED Home with Support Services',
    'ED Reg/Triaged LWBS',
    'ED Reg LWBS',
    'ED Reg/Triaged/Assess LWBS',
    'ED Reg/Triaged/Assess LAMA',
    'Left Against Medical Advice',
    'No Return from Pass'
]

In [412]:
### Create the new column in the data
def map_admission(x):
    if x in admitted_categories:
        return 1
    elif x in not_admitted_categories:
        return 0
    else:
        return None  # safety check

df_clean4['admitted'] = df_clean4['disposition'].apply(map_admission)

In [413]:
print(f'Number of records in the data set after cleaning: {len(df_clean4)}')

Number of records in the data set after cleaning: 911055

In [414]:
df_clean4.info()

<class 'pandas.core.frame.DataFrame'>
Index: 911055 entries, 0 to 912152
Data columns (total 34 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   client_id                911055 non-null  int64
 1   visit_id                 911055 non-null  int64
 2   postal_code              899101 non-null  object
 3   ED                       911055 non-null  object
 4   gender                   911055 non-null  category
 5   age                      911055 non-null  float64
 6   arrival_time             911055 non-null  datetime64[ns]
 7   triage_time              910898 non-null  datetime64[ns]
 8   CTAS                     911055 non-null  object
 9   tot_lab_orders           469110 non-null  float64
 10  tot_lab_test_ordered     469110 non-null  float64
 11  avg_lab_order_time_min   439750 non-null  float64
 12  tot_diag_orders          309396 non-null  float64
 13  tot_diag_test_ordered    309396 non-null  float64
 14  avg_diag_order_time_min  296828 non-null  float64
 15  provider.Type            734323 non-null  object
 16  Consult.Service          192167 non-null  object
 17  init_assess_time         910948 non-null  datetime64[ns]
 18  First.MD.Key             734323 non-null  float64
 19  last_contact_time        911055 non-null  datetime64[ns]
 20  disposition              911055 non-null  object
 21  LOS_Hr                   911055 non-null  float64
 22  wait_time_Hr             910948 non-null  float64
 23  arrival_mode             911055 non-null  object
 24  ED_complaint             911055 non-null  object
 25  chief_complaint          911055 non-null  object
 26  period_of_day            911055 non-null  object
 27  day_of_week              911055 non-null  object
 28  season                   911055 non-null  object
 29  holiday                  911055 non-null  object
 30  service_time             910948 non-null  timedelta64[ns]
 31  service_time_min         910948 non-null  float64
 32  previous_visits          911055 non-null  Int64
 33  admitted                 911055 non-null  int64
dtypes: Int64(1), category(1), datetime64[ns](4), float64(11), int64(3), object(13), timedelta64[ns](1)
memory usage: 238.1+ MB

In [415]:
### Save the cleaned data set as a CSV file:

df_clean4.to_csv('ED_Cleaned_Data.csv', index=False)